### ISSUE TITLE
Small error in Jetibox behavior

### ISSUE THREAD

**Issue by RC-Thoughts** [DevFor8/Mav2Duplex#9]
The lines 366-367 in Mav2EX/Mav2EX.ino are

```
char msg_line1[LCDMaxPos / 2];
char msg_line2[LCDMaxPos / 2];
```
When they should be 
```
char msg_line1[LCDMaxPos / 2 + 1];
char msg_line2[LCDMaxPos / 2 + 1];
```
to display 16 characters per line correctly. Now you can show 1x15 and 1x16, not 2x16.

**Comment by RadekVoltr** [comment]
thanks for report, I just pushed it into master
